homepage/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home')
]

inquiries/urls.py
from django.urls import path
from . import views


app_name = 'inquiries'
urlpatterns = [
    path('inquiry/', views.InquiryFormView.as_view(), name='inquiry'),
    path('success/', views.InquirySuccessView.as_view(), name='success'),
    path('event-booking/', views.EventBookingView.as_view(), name='event-booking'),
    path('<str:slug>/', views.EventAdminInquiryFormView.as_view(), name='event-admin-inquiry'),
    path('<str:slug>/event-success/', views.EventInquirySuccessView.as_view(), name='event-success'),
]

nep_env_treks/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('homepage.urls')),
    path('packages/', include('packages.urls', namespace='packages')),
    path('inquiries/', include('inquiries.urls', namespace='inquiries')),
    path('information/', include('information.urls', namespace='information')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.views.generic import TemplateView
from destinations.models import Destination
from packages.models import Activity, Package, SpecialEvent


class HomePageView(TemplateView):
    template_name = 'homepage/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        destinations = Destination.objects.all()
        activities = Activity.objects.all()
        packages = Package.objects.all()
        special_event = SpecialEvent.objects.filter(is_active=True).first()

        context['destinations'] = destinations
        context['activities'] = activities
        context['packages'] = packages
        context['special_event'] = special_event

        return context

homepage/templates/homepage/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<script defer src="{% static 'js/index.js' %}"></script>

{% endblock %}

{% block content %}
{% include 'nav.html' %}

<a href="{% url 'inquiries:inquiry' %}" id="request">
    Make an Inquiry
</a>


<header>
    <img src="{% static 'img/title-bg.jpg' %}">

    <section>
        <h2>
            Plan the perfect trip to Nepal
        </h2>

        <form action="{% url 'packages:search' %}">
            <select name="destination">
                <option selected value="">Anywhere in Nepal</option>

                {% for destination in destinations %}
                    <option value="{{ destination.id }}">
                        {{ destination.name }}
                    </option>
                {% endfor %}
            </select>

            <select name="activity">
                <option selected value="">Any trip type</option>

                {% for activity in activities %}
                    <option value="{{ activity.id }}">
                        {{ activity.name }}
                    </option>
                {% endfor %}
            </select>

            <button>
                <i class="fas fa-search"></i>
                View Packages
            </button>
        </form>

        <!-- <div class="request">
            <a href="{% url 'inquiries:inquiry' %}">Request Info</a>
        </div> -->
    </section>
</header>

{% if special_event %}
<section id="special-banner">
    <a href="{% url 'packages:event' event_slug=special_event.slug %}" class="banner">
        <h3>{{ special_event.title }}</h3>
        <h4>{{ special_event.description }}</h4>
        <p> Click here to explore featured packages with special rates </p>
    </a>
</section>
{% endif %}

<section id="trip-types">
    {% for activity in activities|slice:":6" %}
        <a href="{% url 'packages:search' %}?activity={{ activity.id }}" class="trip-type">
            <img src=" {{ activity.header_image.url }}">
            <div class="name">{{ activity.name }}</div>
        </a>
    {% endfor %}
</section>

<section id="top-destinations">
    <div class="title">
        Top Destinations
    </div>
    {% for destination in destinations|slice:":4" %}
    <a href="{% url 'packages:search' %}?destination={{ destination.id }}" class="destination">
        <img src="{{ destination.header_image.url }}">
        <div class="name">{{destination.name}}</div>
        <div class="info">{{ destination.package_set.count }} packages</div>

    </a>
    {% endfor %}
</section>

<section id="package-deals">
    <div class="title">
        Top Packages
    </div>

    {% for package in packages|slice:":6" %}
    <a href="{{ package.get_absolute_url }}" class="package-thumbnail">
        <img src="{{ package.header_image.url }}">
        <div class="info">
            <div class="name">
                {{ package.title }}
            </div>
            <div class="details">
                {% for destination in package.destinations.all %}
                <span>
                    <i class="fas fa-map-marker-alt"></i>
                    {{ destination.name }}
                </span>
                {% endfor %}
                <span>
                    <i class="fas fa-calendar"></i>
                    {{ package.no_of_days }} days
                </span>
            </div>

            {% if package.min_price %}
            <div class="price">
                {% if package.max_price != package.min_price %}
                ${{ package.min_price }} - ${{ package.max_price }}
                {% else %}
                ${{ package.min_price }}
                {% endif %}
            </div>
            {% endif %}
        </div>
    </a>
    {% endfor %}
</section>

<section id="explore">
    <h2>
        Explore Nepal
    </h2>

    <div class="summary-2">
        <a href="#" class="item">
            <span>8</span>
            Cultural Heritages
        </a>

        <a href="#" class="item">
            <span>2</span>
            Natural Heritages
        </a>

        <a href="#" class="item">
            <span>8</span>
            Peaks over 8000 meters
        </a>
    </div>

    <div class="links">
        <a href="#">About Nepal</a>
        <a href="#">Geography</a>
        <a href="#">Climate</a>
        <a href="#">Culture</a>
        <a href="#">History</a>
    </div>
</section>

{% include 'footer.html' %}
{% endblock %}