homepage/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home')
]

information/urls.py
from django.urls import path

from . import views

app_name = "information"

urlpatterns = [
    path('<key>/', views.InformationView.as_view(), name='information')
]

nep_env_treks/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('homepage.urls')),
    path('packages/', include('packages.urls', namespace='packages')),
    path('inquiries/', include('inquiries.urls', namespace='inquiries')),
    path('information/', include('information.urls', namespace='information')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Nepal Environmental Treks and Expeditions{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow|Comfortaa|Oswald|Open+Sans|Acme|Bebas+Neue&display=swap" rel="stylesheet">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.6/js/standalone/selectize.min.js" integrity="sha512-pgmLgtHvorzxpKra2mmibwH/RDAVMlOuqU98ZjnyZrOZxgAR8hwL8A02hQFWEK25V40/9yPYb/Zc+kyWMplgaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.6/css/selectize.bootstrap5.min.css" integrity="sha512-w4sRMMxzHUVAyYk5ozDG+OAyOJqWAA+9sySOBWxiltj63A8co6YMESLeucKwQ5Sv7G4wycDPOmlHxkOhPW7LRg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" integrity="sha512-57oZ/vW8ANMjR/KQ6Be9v/+/h6bq9/l3f0Oc7vn6qMqyhvPd1cvKBRWWpzu0QoneImqr2SkmO4MSqU+RpHom3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" integrity="sha512-ELV+xyi8IhEApPS/pSj66+Jiw+sOT1Mqkzlh8ExXihe4zfqbWkxPRi8wptXIO9g73FSlhmquFlUOuMSoXz5IRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://kit.fontawesome.com/67b15b82e9.js" crossorigin="anonymous"></script>

    <script defer src="{% static 'js/base.js' %}"></script>

    {% block head %}

    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/footer.html
<footer>

    <section>
        <h3>About</h3>

        <a href="{% url 'information:information' key='company_info' %}">About Us</a>
        <a href="{% url 'information:information' key='contact' %}">Contact</a>
        <a href="#">Faq</a>
        <a href="#">Sitemap</a>
    </section>

    <section>
        <h3>Quick Links</h3>

        <a href="#">Visa Info</a>
        <a href="#">Health and Safety</a>
        <a href="#">Travel Insurance</a>
    </section>

    <section>
        <h3>Contact</h3>

        <a href="mailto:envtrek@gmail.com">envtrek@gmail.com</a>
        <a href="tel:+9779851031532">Mobile: +977 985103152</a>
        <a href="tel:+97715906003">Tel: +977 1 5906003</a>
        <a href="fax:+97715906100">Fax: +977 1 5906100</a>
    </section>

    <section>
        <h3>Address</h3>
        
        <a href="#">Thamel, Kathmandu, Nepal</a>
        <a href="#">P.O.Box: 25728</a>

        <div class="map-container">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.102485139767!2d85.30992907623325!3d27.714121825191334!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb18fd7455352f%3A0xfb9d7c23039f5f!2sNepal%20Environmental%20Treks%20and%20Expedition%20Pvt.%20Ltd.!5e0!3m2!1sen!2sus!4v1684017441371!5m2!1sen!2sus"
                style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </section>
</footer>

<div id="status">
    Copyright © Nepal Environmental Treks &amp; Expedition Pvt. Ltd. 2020. All Rights Reserved.
</div>

templates/nav.html
{% load static %}
<nav {% if elevate_nav %}class="elevated"{% endif %}>
    <a href="/" class="left">
        <h1>
            <img src="{% static 'img/logo.png' %}">
            Nepal Environmental Treks &amp; Expedition
        </h1>
    </a>

    <div class="right"></div>
</nav>